### ISSUE TITLE
replace is not defined error

### ISSUE THREAD

**Issue by accateo** [guileen/node-sendmail#18]
I follow the guide to install sendmail and I write a simple piece of code to send a test mail.
I don't know why but I have this error:

`Cannot read property 'replace' of undefined`

Why? Can you help me? 
In the code I have all the fields: from,to,subject,text and html...

**Comment by Geex-Renzo** [comment]
Can you show us the full code block?

**Comment by accateo** [comment]
`var sendmail = require('sendmail')();
 sendmail({
            from: '------------',
            to: '----------------- ',
 
            subject: 'test sendmail',
            text: 'test sendmail',
            html: 'Mail of test sendmail ',
          }, function(err, reply) {
            console.log(err && err.stack);
            console.dir(reply);
        });`

sendmail() is called in another function...

**Comment by Geex-Renzo** [comment]
I have found the reason why it doesn't work...
The version we've all downloaded on NPM is v0.1.1
```
root@geex-hosting:~/test/nodejs/mail# npm install node-mailer
/root/test/nodejs/mail
├── node-mailer@0.1.1 
├── nodemailer@2.5.0 
├── nodemailer-sendmail-transport@1.0.0 
└── sendmail@0.2.2 
```
But the version here on GitHub is v0.3.0
In the latest version, the `HTML` property is added, but in 0.1.1 it's now known yet, so you omitted the property `content` and it tries to do a replace on an `undefined`, which makes it crash.

There are 3 solutions:
1. Manually install node-mailer and it'll be fixed (short-term)
2: The owner of the package should give someone access to the NPM account, so it can be properly updated (I'm willing to do so)

**Comment by accateo** [comment]
MM ok. So if I install node-mailer (npm install nodemailer?) and import it, I'll fix the problem?

**Comment by Geex-Renzo** [comment]
It should, let us know if it did!

**Comment by GreenPioneer** [comment]
@Geex-Renzo  im with you on your second solution

**Comment by GreenPioneer** [comment]
Let us us know if theres anything else you need @accateo

**Comment by accateo** [comment]
Mmm no...I have imported nodemailer, but I have the same error. Are you sure that is enough add "var nodemailer = require('nodemailer');"?
Do you know other packages for the sending of the mails?

**Comment by GreenPioneer** [comment]
@accateo  Can you show us exactly what your trying to do and the whole error log. [Make a gist ](https://gist.github.com/)

**Comment by accateo** [comment]
Simply I want to send an email to an address. So, I installed sendmail and nodemailer, but nothing works. If you have a suggestion to do this, also in another way, it would be amazing. 
The code is very simple:
`var sendmail = require('sendmail')();
var nodemailer = require('nodemailer');
sendmail({
    from: 'no-reply@yourdomain.com',
    to: 'test@qq.com, test@sohu.com, test@163.com ',
    subject: 'test sendmail',
    html: 'Mail of test sendmail ',
  }, function(err, reply) {
    console.log(err && err.stack);
    console.dir(reply);
});`

**Comment by Geex-Renzo** [comment]
First please run the following commands in your terminal, since after I've run those, it works:
`npm uninstall sendmail && npm install sendmail`

**Comment by GreenPioneer** [comment]
@accateo  try @Geex-Renzo  snippet and then verify the version you have installed which should be 1.0.0 >  Lastly try our the simple example and put in the proper emails. https://github.com/guileen/node-sendmail/blob/master/examples/simple.js

**Comment by accateo** [comment]
When I try to reinstall, I have this in the console

`npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sendmail"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.3.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer fixed-data-table@0.6.3 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer google-maps-react@1.0.18 wants react@~0.14.8 || ^15.0.0
npm ERR! peerinvalid Peer react-bootstrap@0.29.5 wants react@>=0.14.0
npm ERR! peerinvalid Peer react-dom@15.3.0 wants react@^15.3.0
npm ERR! peerinvalid Peer react-geolocated@0.4.1 wants react@>= 0.11.2 < 16.0.0
npm ERR! peerinvalid Peer react-googlemaps@0.4.0 wants react@>=0.12.1
npm ERR! peerinvalid Peer react-router@2.6.1 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-select@1.0.0-beta14 wants react@^0.14 || ^15.0.0-rc || ^15.0
npm ERR! peerinvalid Peer reactable@0.14.0 wants react@* || ^0.14.0
npm ERR! peerinvalid Peer react-addons-create-fragment@15.3.1 wants react@^15.3.1
npm ERR! peerinvalid Peer react-bootstrap-table@2.5.2 wants react@^0.14.3 || ^15.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Utente\Desktop\sito\unishare2\npm-debug.log`

**Comment by Geex-Renzo** [comment]
That's a problem in the `react` structure you got there, that's not a problem for this module...
You might want to fix that first. Ask StackOverflow if they could help you with that.
As soon as that is fixed, you'll probably be able to install it just fine

**Comment by accateo** [comment]
Ok, I resolved the problem in the console, but now when I try to send an email I have only this error:

`bundle.js:80563 Uncaught TypeError: dns.resolveMx is not a function`

Suggestions?

**Comment by saydullokhamroyev** [comment]
PS C:\Users\Saydullo Khamroyev\Pictures\HTML> npm start

> fashion@1.0.0 start C:\Users\Saydullo Khamroyev\Pictures\HTML
> npm run build && pulp serve


> fashion@1.0.0 build C:\Users\Saydullo Khamroyev\Pictures\HTML
> gulp build

C:\Users\Saydullo Khamroyev\Pictures\HTML\gulpfile.js:15
const replace = replace('gulp-replace');
                ^

ReferenceError: replace is not defined
    at Object.<anonymous> (C:\Users\Saydullo Khamroyev\Pictures\HTML\gulpfile.js:15:17)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at execute (C:\Users\Saydullo Khamroyev\Pictures\HTML\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\i
ndex.js:36:18)
    at Liftoff.handleArguments (C:\Users\Saydullo Khamroyev\Pictures\HTML\node_modules\gulp\node_modules\gulp-cli\index.
js:196:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fashion@1.0.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fashion@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Saydullo Khamroyev\AppData\Roaming\npm-cache\_logs\2019-04-08T14_03_51_884Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fashion@1.0.0 start: `npm run build && pulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fashion@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Saydullo Khamroyev\AppData\Roaming\npm-cache\_logs\2019-04-08T14_03_52_019Z-debug.log
