### ISSUE TITLE
Feature request: DKIM signing

### ISSUE THREAD

**Issue by download13** [guileen/node-sendmail#22]
This would help a lot to make mail sent from this module look more legitimate.

The DKIM signing spec is here: http://dkim.org/specs/rfc4871-dkimbase.html#rfc.section.5.1

And a module that would probably make it a lot easier is here: https://github.com/andris9/dkim-signer

I can probably make the changes on this. Would you be willing to accept a pull request?

**Comment by GreenPioneer** [comment]
Yea i reviewed your links and I will accept it. I have one request - that you give people the options to turn signatures on and off ( default on ) & the options from `SKIM-SIGNER`
