### ISSUE TITLE
ES2015 only?

### ISSUE THREAD

**Issue by Geex-Renzo** [guileen/node-sendmail#25]
The current version of node-sendmail has the keyword `var` everywhere.
When do you think it's time for this to switch to the ES2015 and only use `const` and `let` since it's more memory efficient?

If that's on the roadmap, I can work it out and submit a pull request.

**Comment by GreenPioneer** [comment]
lets put it on the road map then - im down to accept that pr

**Comment by Geex-Renzo** [comment]
#27 ES2015 usage
