### ISSUE TITLE
Custom headers for messages

### ISSUE THREAD

**Issue by controversial** [guileen/node-sendmail#29]
It'd be nice if there was a way to provide custom headers for a message. [A `headers` object is documented](https://github.com/guileen/node-sendmail/blob/master/sendmail.js#L270), but there isn't any code that refers to it.

## Context
Certain headers are required in order to prevent Gmail from marking messages as spam.

**Comment by GreenPioneer** [comment]
Would you like to contribute and submit a pr for what you are wanting in the package? I think it could be useful

Yea i see the headers is documented< It must have been something Guileen had in mind for originally but never elaborated on

**Comment by controversial** [comment]
Ah, thanks 😀
