### ISSUE TITLE
sender not working?

### ISSUE THREAD

**Issue by foxhound87** [guileen/node-sendmail#34]
Hello, 

If I set the sender it seems not working when the mail is received on Gmail.
 
Only the email is shown.

Thank You.

**Comment by GreenPioneer** [comment]
Can you elaborate more on what you're experiencing

**Comment by Geex-Renzo** [comment]
@foxhound87 Can you please show us what you'd like to do and a code snippet?

**Comment by foxhound87** [comment]
I have something like this:

```javascript
sendmail({
  to: 'to@mail.com',
  from: 'from@mail.com',
  sender: 'Sender Name',
  subject: '...',
  html: '...',
});
```

when the mail is received I see:

`from: from@mail.com`

But I expected to see:

`from: Sender Name <from@mail.com>`

otherwise, what's the purpose of the `sender` prop, and how can I achieve that?

Thank You.

**Comment by Geex-Renzo** [comment]
The full object is parsed by a module called `Mailcomposer` you can view all the properties used [here](https://nodemailer.com/extras/mailcomposer/#e-mail-message-fields)
If that isn't working, change `sender` to `from` like what you're expecting to see.

```
sendmail({
  to: 'to@mail.com',
  from: 'Sender Name <from@mail.com>',
  subject: '...',
  html: '...',
});
```

**Comment by foxhound87** [comment]
@Geex-Renzo got it, it's working. thank you!
