### ISSUE TITLE
Email shows up in spam

### ISSUE THREAD

**Issue by jtrugman** [guileen/node-sendmail#47]
Whenever an email is sent from an AWS server the email gets flagged in the spam filter. I tried setting up SPF records however, it is still in spam. 

Did you ever encounter this problem? If so where you able to fix it?

Thanks,
Justin

**Comment by GreenPioneer** [comment]
Where are all of the emails going to? Gmail?

I have not encountered that one specifically because none of my apps run on AWS

@Geex-Renzo  do you have some insight here?

**Comment by jtrugman** [comment]
The emails were going to Gmail

**Comment by GreenPioneer** [comment]
@jtrugman honestly `@gmail.com` I have never been able to get to work. They have always blocked my emails with `sendmail`
