### ISSUE TITLE
It fails to send mail when it's populated

### ISSUE THREAD

**Issue by ktjd123** [guileen/node-sendmail#51]
## Expected Behavior

email can't be sent when it's populated

it should be able to send multiple request

## Current Behavior

It's delayed or failed

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by GreenPioneer** [comment]
@ktjd123 - im late to the party here but
