### ISSUE TITLE
Dkim and Gsuite

### ISSUE THREAD

**Issue by CryptorClub** [guileen/node-sendmail#54]
Hello. I setup SPF and DKIM public key from gsuite in domain records, but script don't recognize it and send mail without DKIM signature. How to check this?

sendmail.js file strings
```
  const dkimPrivateKey = (options.dkim || {}).privateKey;
  const dkimKeySelector = (options.dkim || {}).keySelector || 'google';
  const devPort = options.devPort || -1;
  const devHost = options.devHost || 'localhost';
  const smtpPort = options.smtpPort || 25
  const smtpHost = options.smtpHost || -1
```

DNS TXT record
`google._domainkey.domain.com`

dkim instead of google for txt record and key selector I've also try.

**Comment by GreenPioneer** [comment]
@CryptorClub im sorry im getting to this issue this late

Did you solve your issued already or still need help ?

**Comment by CryptorClub** [comment]
Hello. Thanks for response. I still not setup DKIM
Is I need host file with private key or something? Will be happy for hint. Because don't like that letters are not encrypted...

Thanks!

**Comment by GreenPioneer** [comment]
@CryptorClub - I dropped the ball on this one altogether - reopen this if it's still an issue you need help with
