### ISSUE TITLE
Can't suppress the log output

### ISSUE THREAD

**Issue by getify** [guileen/node-sendmail#61]
I have these options set:

```js
silent: true,
logger: {
   debug: () => {},
   info: () => {},
   warn: () => {},
   error: () => {},
},
```

But when I send an email (like to gmail), I get the whole sending session logged to my console. Is there any option I'm missing to suppress that?

**Comment by getify** [comment]
Nevermind, sorry. Had the config specified in the wrong spot.

**Comment by GreenPioneer** [comment]
Hey Kyle,

No worries - let me know if you have any other questions

Jason
