### ISSUE TITLE
Error, authentication is missing

### ISSUE THREAD

**Issue by CarmeloCampos** [guileen/node-sendmail#66]
I am using sendmail.js with the source of opentrade, and I am registering my domain for mail.
I get the following error

mx resolved:
MX connection created:
recv tierravivaplanet.com> 220-vmi33249.contabo.host ESMTP Exim 4.92 # 2 Sat, 31 Aug 2019 16:03:31 -0500
recv tierravivaplanet.com> 220-We do not authorize the use of this system to transport unsolicited,
recv tierravivaplanet.com> 220 and / or bulk e-mail.
send tierravivaplanet.com> EHLO tierravivaplanet.com
recv tierravivaplanet.com> 250-vmi33249.contabo.host Hello 149.212.239.35.bc.googleusercontent.com [35.239.212.149]
recv tierravivaplanet.com> 250-SIZE 52428800
recv tierravivaplanet.com> 250-8BITMIME
recv tierravivaplanet.com> 250-PIPELINING
recv tierravivaplanet.com> 250-STARTTLS
recv tierravivaplanet.com> 250 HELP
send tierravivaplanet.com> MAIL FROM: <no_reply@tierravivaplanet.com>
recv tierravivaplanet.com> 250 OK
send tierravivaplanet.com> RCPT TO: <support@tierravivaplanet.com>
recv tierravivaplanet.com> 550 SMTP AUTH is required for message submission on port 587
SMTP responds error code 550
Error with your mail server: SMTP code: 550 msg: 550 SMTP AUTH is required for message submission on port 587

I don't know where to put the keys for smtp access

**Comment by GreenPioneer** [comment]
@CarmeloCampos  I think @lacari3ff is spot on
