### ISSUE TITLE
Example on your site incorrect?

### ISSUE THREAD

**Issue by guidocalvano** [guileen/node-sendmail#9]
Your example on your site is incorrect:

https://npmjs.org/package/sendmail

sendmail = require('sendmail').sendmail;

it should be this right? That is what it says on the github page. 

sendmail = require( 'sendmail')() ;

**Comment by El4a** [comment]
Tbh, I still can't get the example to work

**Comment by dopatraman** [comment]
I also cannot get the example to work.

**Comment by guileen** [comment]
It should work now, make sure change to your own mail address, and check the junk mail in your mailbox.
